# Menu
menu:
  首页: /
  归档: /archives
  分类: /gallery
  关于: /about
  友链: /links
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/avatar.gif

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/avatar1.gif

# Content
excerpt_link: Read More...

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # true
  clientID: d8eb36db7718caad6739
  clientSecret: e3922064fd0dd860b593102f2d4641cde7a07e0f
  repo: hustcsxg.github.io
  owner: hustcsxg
  admin: hustcsxg

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'

# Katex Support
katex:
  enable: false # true
  allpost:
  copy_tex:
